name: calculator
description: A simple calculator app built with Flutter.

publish_to: 'none' # Remove this line if you want to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"  # Adjust the SDK version as necessary
  # or use the latest stable SDK version
  # sdk: "^3.5.0"

dependencies:
  flutter:
    sdk: flutter
  # Add any other dependencies here
  # expressions: ^0.4.11  # Remove or comment this out if not needed

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
